# Generated by Django 2.0.5 on 2018-05-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id_bill', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('date_of_bill', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('promotion', models.FloatField()),
                ('sum_price', models.FloatField(null=True)),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Bills')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_customer', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('FM', 'Female')], max_length=5)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('producter', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('base_price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_staff', models.CharField(max_length=30)),
                ('birth', models.DateField()),
                ('phone', models.CharField(max_length=12)),
                ('id_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Department')),
            ],
        ),
        migrations.AddField(
            model_name='billsdetail',
            name='id_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Products'),
        ),
        migrations.AddField(
            model_name='billsdetail',
            name='id_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Staff'),
        ),
        migrations.AddField(
            model_name='bills',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Customer'),
        ),
    ]
